/**
 * Lista curada de icones (nomes de componentes da biblioteca lucide-react)
 * disponiveis para uma organizacao escolher ao criar uma conquista propria.
 * Mantida tambem no painel admin para renderizar o seletor visual — os nomes
 * precisam corresponder exatamente aos exportados por lucide-react.
 */
export const ACHIEVEMENT_ICONS = [
  "Trophy",
  "Medal",
  "Award",
  "Star",
  "Crown",
  "Flag",
  "MapPin",
  "Map",
  "Compass",
  "Navigation",
  "Route",
  "Footprints",
  "Mountain",
  "MountainSnow",
  "Trees",
  "TreePine",
  "Waves",
  "Sun",
  "Sunrise",
  "Sunset",
  "Moon",
  "CloudSun",
  "Umbrella",
  "Camera",
  "Binoculars",
  "Backpack",
  "Bike",
  "Bus",
  "Car",
  "TrainFront",
  "Plane",
  "Ship",
  "Anchor",
  "Tent",
  "Landmark",
  "Church",
  "Castle",
  "Building",
  "Building2",
  "Palette",
  "Music",
  "BookOpen",
  "Utensils",
  "Coffee",
  "IceCreamCone",
  "Pizza",
  "Cake",
  "Gift",
  "PartyPopper",
  "Sparkles",
  "Heart",
  "ThumbsUp",
  "Users",
  "Handshake",
  "Calendar",
  "Clock",
  "Fish",
  "Bird",
  "Leaf",
  "Flower2",
  "Gem",
  "Coins",
  "Wallet",
  "Ticket",
  "Key",
  "ShieldCheck",
  "Target",
  "Rocket",
  "Globe",
  "Lightbulb",
  "Puzzle",
  "Telescope",
  "Sailboat",
  "FerrisWheel",
  "Drama",
  "Eye",
] as const;

export type AchievementIcon = (typeof ACHIEVEMENT_ICONS)[number];

export const MAX_ACHIEVEMENTS_PER_ORGANIZATION = 10;
